#! /bin/sh

###################
# CONFIGURE BSPWM #
###################
bspc config border_width        2
bspc config window_gap          6
bspc config top_padding         34
bspc config split_ratio         0.6
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config initial_polarity    first_child

bspc config normal_border_color  "#2d2d2d"
bspc config active_border_color  "#4c555d"
bspc config focused_border_color "#d64935"
bspc config urgent_border_color  "#ad0000"

bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true
bspc config focus_by_distance       true
bspc config focus_follows_pointer   true

bspc monitor HDMI1 -d NET IM I
bspc monitor HDMI2 -d I II III

#bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a chromium desktop=NET
bspc rule -a skype desktop=IM

bspc rule -a pcmanfm floating=on
bspc rule -a pavucontrol floating=on
bspc rule -a xarchiver floating=on
bspc rule -a galculator floating=on
bspc rule -a gmpc floating=on
bspc rule -a vlc floating=on
bspc rule -a nitrogen floating=on
bspc rule -a virt-manager floating=on


###########
# AUTORUN #
###########
xrandr --output HDMI2 --primary --output HDMI1 --right-of HDMI2

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

pcmanfm -d &
nitrogen --restore
xscreensaver -no-splash &
compton -cCGf -D 5 -t "-5" -l "-5" -r 3 -b

# Panel & Systray
~/.config/panel/panel.sh &
trayer --edge top --align right --widthtype pixel --width 158 --height 20 \
--iconspacing 2 --expand false --transparent true --alpha 0 --tint 4281150765 \
--distancefrom right --distance 3 &

# Systray applets
pa-applet &
nm-applet &
clipit &
synergy &
(sleep 4 && skype_noecho) &
