#! /bin/sh

###################
# CONFIGURE BSPWM #
###################
bspc config border_width        2
bspc config window_gap          5
bspc config top_padding         27
bspc config split_ratio         0.6
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config initial_polarity    first_child

bspc config normal_border_color  "#2d2d2d"
bspc config active_border_color  "#4c555d"
bspc config focused_border_color "#d64935"
bspc config urgent_border_color  "#ad0000"

bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true
bspc config focus_by_distance       true
bspc config focus_follows_pointer   true

bspc monitor HDMI1 -d NET IM I
bspc monitor HDMI2 -d I II III

#bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a chromium desktop=NET
bspc rule -a Skype desktop=IM

bspc rule -a Pavucontrol state=floating
bspc rule -a Galculator state=floating
bspc rule -a Sonata state=floating
bspc rule -a Vlc state=floating
bspc rule -a Nitrogen state=floating


###########
# AUTORUN #
###########
xrandr --output HDMI2 --primary --output HDMI1 --right-of HDMI2

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

pcmanfm -d &
nitrogen --restore
xscreensaver -no-splash &
compton -b

# Panel & Systray
#~/.config/panel/panel.sh &
yabar &
(sleep 4 & stalonetray) &

# Systray applets
pa-applet &
nm-applet &
clipit &
synergy &
(sleep 4 && skype) &
